base:
    seed: &seed 42
model:
    type: Llama
    path: /home/zonglin/large-file-storage/meta-llama/Llama-2-7b-hf
    tokenizer_mode: slow
    torch_dtype: auto
calib:
    name: pileval
    download: True
    path: calib data path
    n_samples: 128
    bs: -1
    seq_len: 512
    preproc: txt_general_preproc
    seed: *seed
eval:
    eval_pos: [pretrain, fake_quant, transformed]
    name: wikitext2
    download: True
    path: eval data path
    seq_len: 2048
    # For 7B / 13B model eval, bs can be set to "1", and inference_per_block can be set to "False".
    # For 70B model eval, bs can be set to "20", and inference_per_block can be set to "True".
    bs: 1
    inference_per_block: False
quant:
    method: Awq
    weight:
        bit: 4
        symmetric: True
        granularity: per_group
        group_size: 128
        need_pack: True
    special:
        trans: True
        trans_version: v2
        weight_clip: True
    quant_out: True
save:
    save_vllm: True
    save_trans: True
    save_fake: True
    save_path: runs/llm2-7b
